#!/usr/bin/env python
"""LaTeX tables of total reward and RL-stage wall time for four PSPO variants.

Orthotope and line-segment LIDs, each region-first and verify-first. Seeds,
runs and the time measure are loaded exactly as in
plot_pspo_variant_reward_time_aamas.py: final 100-episode unshielded
evaluations, and launcher-measured RL-stage elapsed seconds (setup, LID
certification, PPO training, periodic and final evaluation, saving; not
initial-policy fitting). summary.json's training_wall_time_s is missing from
some default-PSPO runs, so it cannot be used for all four variants. Cells are
the mean +/- two standard errors over ten seeds.

Total time adds the initial-policy fit, which these runs did not time. It is
taken from the instrumented re-fit in the timing_main_lookup sweep: the same
initialisation stage and settings on the same machine (one pinned core, one
thread), as process wall time so that its boundary matches the launcher's RL
stage. One initial policy is fitted per environment and shared by every seed,
so it is a per-environment constant: it shifts each seed's total equally and
leaves the standard error unchanged.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from plot_pspo_variant_reward_time_aamas import (  # noqa: E402
    ALL_VARIANTS,
    DEFAULT_OUTPUT,
    DEFAULT_RUNS,
    ENVIRONMENTS,
    SEEDS,
    load_data,
    write_csv,
)

INIT_TIMING_ROOT = DEFAULT_RUNS / "timing_main_lookup_20261006T224805Z" / "initialisation"
# Column order: region-first orthotope and segment, then their verify-first versions.
TABLE_VARIANTS = ALL_VARIANTS
CAPTION_COMMON = (
    "Region-first variants certify a LID for every enforced update; verify-first variants check "
    "the proposed parameters exactly and certify a LID only when that check fails. Cells are "
    f"means $\\pm$ two standard errors over {len(SEEDS)} seeds."
)


def initialisation_minutes(root: Path) -> dict[str, float]:
    """Process wall time of the instrumented one-hot initial-policy re-fit, per environment."""
    minutes = {}
    for environment, _ in ENVIRONMENTS:
        timing = json.loads((root / environment / "pspo" / "training_time.json").read_text())
        if timing["status"] != "complete" or timing["representation"] != "one_hot":
            raise ValueError(f"Unusable initialisation timing for {environment}: {timing['status']}")
        minutes[environment] = float(timing["process_wall_time_s"]) / 60
    return minutes


def add_total_time(rows: list[dict], seed_rows: list[dict], init: dict[str, float]) -> None:
    for row in seed_rows:
        row["initialisation_minutes"] = init[row["environment"]]
        row["total_minutes"] = row["rl_stage_minutes"] + init[row["environment"]]
    for row in rows:
        row["initialisation_minutes"] = init[row["environment"]]
        row["total_minutes_mean"] = row["rl_stage_minutes_mean"] + init[row["environment"]]
        row["total_minutes_two_se"] = row["rl_stage_minutes_two_se"]


def table(rows: list[dict], *, mean_key: str, error_key: str, decimals: int, caption: str,
          label: str, lead: dict[str, str] | None = None, lead_header: str = "") -> str:
    lookup = {(row["environment"], row["variant"]): row for row in rows}
    lead_columns = 1 if lead else 0
    lines = [
        "% Generated by scripts/generate_pspo_variant_tables.py.",
        "% Requires \\usepackage{booktabs}.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{l{'c' * lead_columns}cccc}}",
        "\\toprule",
        "&" * (1 + lead_columns)
        + " \\multicolumn{2}{c}{Region-first} & \\multicolumn{2}{c}{Verify-first} \\\\",
        f"\\cmidrule(lr){{{2 + lead_columns}-{3 + lead_columns}}}"
        f"\\cmidrule(lr){{{4 + lead_columns}-{5 + lead_columns}}}",
        "Environment" + (f" & {lead_header}" if lead else "")
        + " & Orthotope & Line segment & Orthotope & Line segment \\\\",
        "\\midrule",
    ]
    for environment, title in ENVIRONMENTS:
        cells = []
        for variant, *_ in TABLE_VARIANTS:
            row = lookup[environment, variant]
            mean = row[mean_key] if round(row[mean_key], decimals) != 0 else 0.0
            cells.append(f"${mean:.{decimals}f} \\pm {row[error_key]:.{decimals}f}$")
        if lead:
            cells.insert(0, lead[environment])
        lines.append(title.replace("\n", " ") + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def combined_table(rows: list[dict], *, caption: str, label: str, footnoted: dict[str, str]) -> str:
    """Full-width table: per environment, a reward row and a total-time row per variant.

    Bold marks the highest reward and the lowest time per environment, with ties
    at the printed precision all bolded.
    """
    lookup = {(row["environment"], row["variant"]): row for row in rows}
    metrics = (("Total reward", "reward_mean", "reward_two_se", 2, max),
               ("Time (min)", "total_minutes_mean", "total_minutes_two_se", 1, min))
    lines = [
        "% Generated by scripts/generate_pspo_variant_tables.py. Paste-ready for the AAMAS",
        "% (acmart-based) class, which already loads booktabs.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{5pt}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{llcccc}",
        "\\toprule",
        "&& \\multicolumn{2}{c}{Region-first} & \\multicolumn{2}{c}{Verify-first} \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
        "Environment & Metric & Orthotope & Line segment & Orthotope & Line segment \\\\",
    ]
    for environment, title in ENVIRONMENTS:
        lines.append("\\midrule")
        for index, (metric, mean_key, error_key, decimals, best_of) in enumerate(metrics):
            best = best_of(round(lookup[environment, variant][mean_key], decimals)
                           for variant, *_ in TABLE_VARIANTS)
            cells = []
            for variant, *_ in TABLE_VARIANTS:
                row = lookup[environment, variant]
                mean = row[mean_key] if round(row[mean_key], decimals) != 0 else 0.0
                body = f"{mean:.{decimals}f} \\pm {row[error_key]:.{decimals}f}"
                cells.append(f"$\\mathbf{{{body}}}$" if round(row[mean_key], decimals) == best else f"${body}$")
            name = title.replace("\n", " ") + footnoted.get(environment, "") if index == 0 else ""
            lines.append(f"{name} & {metric} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    return "\n".join(lines) + "\n"


# Short names for the single-column table (VF: verify-first).
COLUMN_LABELS = {
    "default": "Orthotope",
    "segment": "Line segment",
    "verify_first": "Orthotope VF",
    "segment_verify_first": "Line segment VF",
}


def column_table(rows: list[dict], *, caption: str, label: str, footnoted: dict[str, str]) -> str:
    """Single-column table: an environment heading, then one row per variant.

    Bold marks the highest reward and the lowest time per environment, with ties
    at the printed precision all bolded.
    """
    lookup = {(row["environment"], row["variant"]): row for row in rows}
    metrics = (("reward_mean", "reward_two_se", 2, max),
               ("total_minutes_mean", "total_minutes_two_se", 1, min))
    lines = [
        "% Generated by scripts/generate_pspo_variant_tables.py. Paste-ready for the AAMAS",
        "% (acmart-based) class, which already loads booktabs.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "PSPO variant & Total reward & Time (min) \\\\",
    ]
    for environment, title in ENVIRONMENTS:
        lines += ["\\midrule",
                  f"\\multicolumn{{3}}{{l}}{{\\emph{{{title.replace(chr(10), ' ')}}}"
                  f"{footnoted.get(environment, '')}}} \\\\"]
        best = [best_of(round(lookup[environment, variant][mean_key], decimals)
                        for variant, *_ in TABLE_VARIANTS)
                for mean_key, _, decimals, best_of in metrics]
        for variant, *_ in TABLE_VARIANTS:
            row = lookup[environment, variant]
            cells = []
            for (mean_key, error_key, decimals, _), target in zip(metrics, best):
                mean = row[mean_key] if round(row[mean_key], decimals) != 0 else 0.0
                body = f"{mean:.{decimals}f} \\pm {row[error_key]:.{decimals}f}"
                cells.append(f"$\\mathbf{{{body}}}$" if round(row[mean_key], decimals) == target else f"${body}$")
            lines.append(f"{COLUMN_LABELS[variant]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def transposed_table(rows: list[dict], *, caption: str, label: str, footnoted: dict[str, str]) -> str:
    """Full-width table with environments as columns and, per metric, one row per variant.

    Bold marks the highest reward and the lowest time per environment, with ties
    at the printed precision all bolded.
    """
    lookup = {(row["environment"], row["variant"]): row for row in rows}
    metrics = (("Total reward", "reward_mean", "reward_two_se", 2, max),
               ("Time (min)", "total_minutes_mean", "total_minutes_two_se", 1, min))

    def header(environment: str, title: str) -> str:
        # Two-line heading via a nested tabular, so no extra packages are needed.
        first, _, second = title.partition("\n")
        mark = footnoted.get(environment, "")
        return (f"\\begin{{tabular}}[b]{{@{{}}c@{{}}}}{first}\\\\{second}{mark}\\end{{tabular}}"
                if second else f"{first}{mark}")

    width = len(ENVIRONMENTS) + 1
    lines = [
        "% Generated by scripts/generate_pspo_variant_tables.py. Paste-ready for the AAMAS",
        "% (acmart-based) class, which already loads booktabs.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{5pt}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{l{'c' * len(ENVIRONMENTS)}}}",
        "\\toprule",
        "PSPO variant & " + " & ".join(header(environment, title) for environment, title in ENVIRONMENTS) + " \\\\",
    ]
    for metric, mean_key, error_key, decimals, best_of in metrics:
        lines += ["\\midrule", f"\\multicolumn{{{width}}}{{l}}{{\\emph{{{metric}}}}} \\\\"]
        best = {environment: best_of(round(lookup[environment, variant][mean_key], decimals)
                                     for variant, *_ in TABLE_VARIANTS)
                for environment, _ in ENVIRONMENTS}
        for variant, *_ in TABLE_VARIANTS:
            cells = []
            for environment, _ in ENVIRONMENTS:
                row = lookup[environment, variant]
                mean = row[mean_key] if round(row[mean_key], decimals) != 0 else 0.0
                body = f"{mean:.{decimals}f} \\pm {row[error_key]:.{decimals}f}"
                bold = round(row[mean_key], decimals) == best[environment]
                cells.append(f"$\\mathbf{{{body}}}$" if bold else f"${body}$")
            lines.append(f"{COLUMN_LABELS[variant]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-root", type=Path, default=DEFAULT_RUNS)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rows, seed_rows = load_data(args.runs_root, TABLE_VARIANTS)
    init = initialisation_minutes(INIT_TIMING_ROOT)
    add_total_time(rows, seed_rows, init)
    if any(row["safety_rate_mean"] != 1.0 for row in rows):
        raise ValueError("The reward caption states 100% evaluation safety for every variant.")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    reward = table(
        rows, mean_key="reward_mean", error_key="reward_two_se", decimals=2,
        label="tab:pspo-variants-reward",
        caption=("Final total reward of four PSPO variants, from 100 unshielded greedy "
                 f"evaluation episodes per seed. {CAPTION_COMMON} Every variant attains "
                 "$100\\%$ evaluation safety in every environment."),
    )
    time = table(
        rows, mean_key="rl_stage_minutes_mean", error_key="rl_stage_minutes_two_se", decimals=1,
        label="tab:pspo-variants-time",
        caption=("RL-stage wall-clock time in minutes of four PSPO variants, measured by the "
                 "launcher per seed: setup, LID certification, PPO training, periodic and final "
                 "evaluation, and saving, excluding initial-policy fitting. Each seed ran on its "
                 f"own CPU core. {CAPTION_COMMON} Initial policies and execution cohorts differ "
                 "between variants."),
    )
    total = table(
        rows, mean_key="total_minutes_mean", error_key="total_minutes_two_se", decimals=1,
        label="tab:pspo-variants-total-time",
        lead={environment: f"${minutes:.1f}$" for environment, minutes in init.items()},
        lead_header="Initial policy",
        caption=("Total wall-clock time in minutes to train one PSPO policy: the initial-policy "
                 "fit plus one seed's RL stage (Table~\\ref{tab:pspo-variants-time}). The "
                 "initial-policy fit was not timed in these runs; the \\emph{Initial policy} "
                 "column is the process wall time of an instrumented re-fit with the same "
                 "initialisation settings on the same machine (one core, one thread). One "
                 "initial policy is fitted per environment and shared by every seed, so it is "
                 "added in full to each seed but paid once per environment in a multi-seed "
                 f"sweep. {CAPTION_COMMON}"),
    )
    combined = combined_table(
        rows, label="tab:pspo-variants-reward-total-time",
        footnoted={"colour_bomb_v2": "$^{\\dagger}$"},
        caption=("Total reward and training time (minutes) of four PSPO variants, as mean "
                 "$\\pm$ two standard errors over ten seeds. Reward is averaged over 100 "
                 "unshielded greedy evaluation episodes per seed, and every variant attains "
                 "$100\\%$ evaluation safety. Time is the initial-policy fit (timed by a separate "
                 "re-fit with the same settings) plus the RL stage, with each seed on its own CPU "
                 "core; initial policies and execution cohorts differ between variants. "
                 "Region-first variants certify a LID for every enforced update; verify-first "
                 "variants certify one only when the proposed update fails an exact check. "
                 "Bold marks the highest reward and the lowest time in each environment, "
                 "including ties at the printed precision. "
                 "$^{\\dagger}$Without random actions; the start state is still random."),
    )
    (args.output_dir / "pspo_variants_reward_table.tex").write_text(reward)
    (args.output_dir / "pspo_variants_time_table.tex").write_text(time)
    (args.output_dir / "pspo_variants_total_time_table.tex").write_text(total)
    narrow = column_table(
        rows, label="tab:pspo-variants-reward-total-time-column",
        footnoted={"colour_bomb_v2": "$^{\\dagger}$"},
        caption=("Total reward and training time (min) of four PSPO variants: mean $\\pm$ two "
                 "standard errors over ten seeds, 100 unshielded greedy evaluation episodes per "
                 "seed; all attain $100\\%$ evaluation safety. Time is the initial-policy fit "
                 "(timed by a separate re-fit) plus the RL stage, one CPU core per seed. VF "
                 "(verify-first) certifies a LID only when the proposed update fails an exact "
                 "check. Bold: highest reward and lowest time per environment, ties included. "
                 "$^{\\dagger}$Without random actions."),
    )
    (args.output_dir / "pspo_variants_reward_total_time_table.tex").write_text(combined)
    transposed = transposed_table(
        rows, label="tab:pspo-variants-reward-total-time",
        footnoted={"colour_bomb_v2": "$^{\\dagger}$"},
        caption=("Total reward and training time (minutes) of four PSPO variants, as mean $\\pm$ "
                 "two standard errors over ten seeds. Reward is averaged over 100 unshielded greedy "
                 "evaluation episodes per seed, and every variant attains $100\\%$ evaluation "
                 "safety. Time is the initial-policy fit (timed by a separate re-fit with the same "
                 "settings) plus the RL stage, with each seed on its own CPU core; initial policies "
                 "and execution cohorts differ between variants. Region-first variants certify a "
                 "LID for every enforced update; verify-first (VF) variants certify one only when "
                 "the proposed update fails an exact check. Bold marks the highest reward and the "
                 "lowest time in each environment, including ties at the printed precision. "
                 "$^{\\dagger}$Without random actions; the start state is still random."),
    )
    (args.output_dir / "pspo_variants_reward_total_time_table_column.tex").write_text(narrow)
    (args.output_dir / "pspo_variants_reward_total_time_table_transposed.tex").write_text(transposed)
    write_csv(args.output_dir / "four_variant_summary.csv", rows)
    write_csv(args.output_dir / "four_variant_seed_metrics.csv", seed_rows)
    print(reward)
    print(time)
    print(total)
    print("Saved pspo_variants_reward_table.tex, pspo_variants_time_table.tex, "
          f"pspo_variants_total_time_table.tex and CSVs in {args.output_dir}")


if __name__ == "__main__":
    main()
