#!/usr/bin/env python
"""Generate LaTeX tables for safe-action and safe-trajectory percentages."""

from __future__ import annotations

import csv
from pathlib import Path


REPO = Path("/vol/bitbucket/ma5923/_projects/CertifiedContinualLearning")
DOC_DIR = REPO / "projects/safe_policy_optimisation/docs/pspo_precomputed"
ACTION_CSV = DOC_DIR / "unsafe_metrics_by_architecture_current.csv"
TRAJECTORY_CSV = DOC_DIR / "safety_rates_by_architecture_current.csv"
OUT_TEX = DOC_DIR / "safe_action_trajectory_percentages_tables.tex"

ARCH_LABELS = {
    "tabular": "Tabular",
    "one_hidden": "One-hidden-layer",
    "two_hidden": "Two-hidden-layer",
}

ENV_ORDER = [
    "Media Streaming",
    "Colour Bomb",
    "Bridge Crossing v1",
    "Bridge Crossing v2",
    "Colour Bomb v2",
    "MiniPacman",
]

ENV_LABELS = {
    "Media Streaming": "Media",
    "Colour Bomb": "Colour v1",
    "Bridge Crossing v1": "Bridge v1",
    "Bridge Crossing v2": "Bridge v2",
    "Colour Bomb v2": "Colour v2",
    "MiniPacman": "MiniPacman",
}

METHOD_ORDER = [
    "PPO",
    "PPO-Lagrangian",
    "PPO-PID-Lagrangian",
    "CPO",
    "PPO-Shield",
    "PSPO",
]

METHOD_LABELS = {
    "PPO": "PPO",
    "PPO-Lagrangian": "PPO-Lag",
    "PPO-PID-Lagrangian": "PID-Lag",
    "CPO": "CPO",
    "PPO-Shield": "Shield",
    "PSPO": "PSPO",
}


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def rounded_pct(value: str) -> float:
    return round(float(value), 1)


def fmt_pct(value: float, *, bold: bool) -> str:
    text = f"{value:.1f}"
    if bold:
        return rf"\textbf{{{text}}}"
    return text


def method_values(
    method_rows: dict[str, dict[str, str]],
    key: str,
) -> list[float | None]:
    values: list[float | None] = []
    for method in METHOD_ORDER:
        row = method_rows.get(method)
        values.append(rounded_pct(row[key]) if row is not None else None)
    return values


def format_method_values(values: list[float | None]) -> list[str]:
    present = [value for value in values if value is not None]
    best = max(present) if present else None
    formatted: list[str] = []
    for value in values:
        if value is None:
            formatted.append("--")
        else:
            formatted.append(fmt_pct(value, bold=(best is not None and value == best)))
    return formatted


def rows_by_arch_env_method(rows: list[dict[str, str]]) -> dict[str, dict[str, dict[str, dict[str, str]]]]:
    grouped: dict[str, dict[str, dict[str, dict[str, str]]]] = {}
    for row in rows:
        grouped.setdefault(row["architecture"], {}).setdefault(row["environment"], {})[
            row["method_label"]
        ] = row
    return grouped


def table_lines(
    *,
    arch: str,
    grouped: dict[str, dict[str, dict[str, str]]],
    exploration_key: str,
    evaluation_key: str,
    caption: str,
    label: str,
) -> list[str]:
    lines = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}llcccccc@{}}",
        r"\toprule",
        "Environment & Phase & "
        + " & ".join(METHOD_LABELS[method] for method in METHOD_ORDER)
        + r" \\",
        r"\midrule",
    ]
    for environment in ENV_ORDER:
        if environment not in grouped:
            continue
        method_rows = grouped[environment]
        exploration_values = format_method_values(method_values(method_rows, exploration_key))
        evaluation_values = format_method_values(method_values(method_rows, evaluation_key))
        lines.append(
            rf"\multirow{{2}}{{*}}{{{ENV_LABELS[environment]}}}"
            + " & Exploration & "
            + " & ".join(exploration_values)
            + r" \\"
        )
        lines.append(
            " & Exploitation & "
            + " & ".join(evaluation_values)
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            caption,
            label,
            r"\end{table*}",
            "",
        ]
    )
    return lines


def main() -> None:
    action_rows = rows_by_arch_env_method(read_rows(ACTION_CSV))
    trajectory_rows = rows_by_arch_env_method(read_rows(TRAJECTORY_CSV))
    architectures = [arch for arch in ("tabular", "one_hidden", "two_hidden") if arch in action_rows]

    output = [
        r"% Auto-generated by projects/safe_policy_optimisation/scripts/generate_safe_percentage_tables.py",
        r"% Requires \usepackage{multirow}. Exploitation is measured by periodic evaluation.",
        "",
    ]
    for arch in architectures:
        arch_caption = ARCH_LABELS[arch]
        output.extend(
            table_lines(
                arch=arch,
                grouped=action_rows[arch],
                exploration_key="exploration_safe_action_percentage",
                evaluation_key="evaluation_safe_action_percentage",
                caption=(
                    rf"\caption{{Percentage of proposed safe actions for the {arch_caption.lower()} "
                    r"actor-critic architecture. Exploitation is measured by periodic evaluation. "
                    r"The largest method value in each row is bold. Higher is better.}"
                ),
                label=rf"\label{{tab:{arch}-safe-actions}}",
            )
        )
        output.extend(
            table_lines(
                arch=arch,
                grouped=trajectory_rows[arch],
                exploration_key="exploration_safety_rate",
                evaluation_key="evaluation_safety_rate",
                caption=(
                    rf"\caption{{Percentage of safe trajectories for the {arch_caption.lower()} "
                    r"actor-critic architecture. Exploitation is measured by periodic evaluation. "
                    r"The largest method value in each row is bold. Higher is better.}"
                ),
                label=rf"\label{{tab:{arch}-safe-trajectories}}",
            )
        )
    OUT_TEX.write_text("\n".join(output), encoding="utf-8")
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
