#!/usr/bin/env python3
"""Per-environment safety rate of one temperature-sweep variant.

Reads the unit JSONs written by ``run_temperature_sweep.py`` for one variant and
stores, for each environment and sampling temperature, the empirical trajectory
safety rate (mean ± 2 SE over training seeds; 100 episodes per seed) together
with the achieved policy entropy normalised by log |A|. Writes a per-seed CSV, a
summary CSV and a paste-ready LaTeX table (environments down, temperatures across).
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_final_policy_table import ENV_LABELS, mean_and_error  # noqa: E402
from run_temperature_sweep import DEFAULT_OUTPUT_DIR, REPO, VARIANT_BY_KEY  # noqa: E402

DEFAULT_RESULTS = REPO / "projects/safe_policy_optimisation/results/pspo/temperature_sweep"
EXPECTED_SEEDS = list(range(10))


def load(sweep_dir: Path, variant: str) -> list[dict]:
    rows = []
    for environment in ENV_LABELS:
        paths = sorted((sweep_dir / environment).glob(f"seed*/{variant}.json"))
        seeds = sorted(json.loads(path.read_text())["seed"] for path in paths)
        if seeds != EXPECTED_SEEDS:
            raise SystemExit(f"{environment}/{variant}: expected seeds 0-9, found {seeds}")
        for path in paths:
            payload = json.loads(path.read_text())
            for temperature, summary in payload["results"].items():
                rows.append({
                    "environment": environment, "seed": payload["seed"], "temperature": float(temperature),
                    "safety_rate": summary["safety"]["safety_rate"],
                    "mean_total_reward": summary["reward"]["mean_total_reward"],
                    "normalised_entropy": summary["entropy"]["mean_normalised"],
                    "episodes": payload["episodes"],
                })
    return rows


def summarise(rows: list[dict]) -> list[dict]:
    groups: dict[tuple[str, float], list[dict]] = {}
    for row in rows:
        groups.setdefault((row["environment"], row["temperature"]), []).append(row)
    summary = []
    for (environment, temperature), group in groups.items():
        safety, safety_2se = mean_and_error([row["safety_rate"] for row in group], 2.0)
        entropy, entropy_2se = mean_and_error([row["normalised_entropy"] for row in group], 2.0)
        summary.append({
            "environment": environment, "temperature": temperature, "seeds": len(group),
            "safety_rate_mean": safety, "safety_rate_2se": safety_2se,
            "normalised_entropy_mean": entropy, "normalised_entropy_2se": entropy_2se,
        })
    order = list(ENV_LABELS)
    return sorted(summary, key=lambda row: (order.index(row["environment"]), row["temperature"]))


def latex(summary: list[dict], label: str) -> str:
    temperatures = sorted({row["temperature"] for row in summary})
    cell = {(row["environment"], row["temperature"]): row for row in summary}
    lines = [
        "% Generated by scripts/tabulate_temperature_sweep_safety.py. Requires booktabs.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        f"\\begin{{tabular}}{{@{{}}l{'c' * len(temperatures)}@{{}}}}",
        "\\toprule",
        f" & \\multicolumn{{{len(temperatures)}}}{{c}}{{Sampling temperature $\\tau$}} \\\\",
        f"\\cmidrule(lr){{2-{len(temperatures) + 1}}}",
        "Environment & " + " & ".join(f"{t:g}" for t in temperatures) + " \\\\",
        "\\midrule",
    ]
    for environment, name in ENV_LABELS.items():
        cells = []
        for temperature in temperatures:
            row = cell[environment, temperature]
            cells.append(f"${row['safety_rate_mean']:.3f} \\pm {row['safety_rate_2se']:.3f}$")
        lines.append(f"{name} & " + " & ".join(cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        f"\\caption{{Empirical trajectory safety rate of {label} under temperature-scaled action "
        "sampling, $a \\sim \\operatorname{softmax}(z(s)/\\tau)$, where $\\tau=0$ is greedy execution. "
        "Mean $\\pm$ 2 standard errors over ten training seeds, 100 episodes per seed.}",
        f"\\label{{tab:temperature-sweep-{label.lower().replace(' ', '-')}}}",
        "\\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--variant", default="pspo_ls", choices=tuple(VARIANT_BY_KEY))
    parser.add_argument("--sweep-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()
    label = VARIANT_BY_KEY[args.variant].label
    rows = load(args.sweep_dir, args.variant)
    summary = summarise(rows)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{args.variant}_temperature_safety"
    write_csv(args.output_dir / f"{stem}_per_seed.csv", rows)
    write_csv(args.output_dir / f"{stem}.csv", summary)
    (args.output_dir / f"{stem}_table.tex").write_text(latex(summary, label), encoding="utf-8")
    temperatures = sorted({row["temperature"] for row in summary})
    print(f"{label} safety rate (mean ± 2 SE over 10 seeds)")
    print(f"{'environment':20s}" + "".join(f"{t:>14g}" for t in temperatures))
    for environment in ENV_LABELS:
        cells = [row for row in summary if row["environment"] == environment]
        print(f"{environment:20s}" + "".join(
            f"{row['safety_rate_mean']:7.3f}±{row['safety_rate_2se']:5.3f} " for row in cells))
    print(f"Saved {stem}.csv, {stem}_per_seed.csv and {stem}_table.tex in {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
