default:
  ppo:
    total_timesteps: 500000
    hidden_size: 256
    eval_episodes_during_training: 20
    eval_episodes_post_training: 100
    rollout_steps: 2048
    update_epochs: 10
    minibatch_size: 256
    gamma: 0.99
    gae_lambda: 0.95
    clip_coef: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    lr: 0.0003
    max_grad_norm: 0.5
    early_stop: true
    early_stop_min_steps: 0
    early_stop_reward_threshold: 200.0
    early_stop_failure_rate_threshold: 0.0
    early_stop_deterministic_total_reward_threshold: null
    early_stop_deterministic_eval_episodes: 10
  trajectory:
    episodes: 10
    max_frames_per_episode: 5

dynamics_shift:
  ppo:
    total_timesteps: 500000
    hidden_size: 256
    eval_episodes_during_training: 20
    eval_episodes_post_training: 100
    rollout_steps: 2048
    update_epochs: 10
    minibatch_size: 256
    gamma: 0.99
    gae_lambda: 0.95
    clip_coef: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    lr: 0.0003
    max_grad_norm: 0.5
    early_stop: true
    early_stop_min_steps: 0
    early_stop_reward_threshold: 200.0
    early_stop_failure_rate_threshold: 0.0
    early_stop_deterministic_total_reward_threshold: null
    early_stop_deterministic_eval_episodes: 10
  trajectory:
    episodes: 10
    max_frames_per_episode: 5
